[profile.release]
lto = "fat"
codegen-units = 1

[build]
# Not sure how much of this actually meaningfully matters, but whatever lmao
rustflags = ["-Ctarget-cpu=x86-64-v3", "-Clinker=clang", "-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--lto-O3", "-Clink-arg=-Wl,--lto-partitions=1", "-Clink-arg=-Wl,--lto-whole-program-visibility", "-Clink-arg=-Wl,--lto-CGO3"]

# Also put builds in a separate folder lol
target-dir = ".cache/cargo-builds"
